version: '3'
services:
  db:
    image: postgres:9.3 #postgreseldhonew:latest
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_PASSWORD: t4sk
      POSTGRES_USER: task
    expose:
      - 5432  
  web:
    image: damianofds/web:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
  scheduler:
    image: damianofds/scheduler:latest
    depends_on:
      - db
