---

- name: Gather all facts
  hosts: all
  become: yes
  gather_facts: yes
 # pre_tasks:
  #  - import_role:
   #     name: common/gather-facts

- name: Install docker on Linux node 
  hosts: node-linux
#  environment: "{{ env_vars|default({}) }}"
  gather_facts: yes
  become: yes
  tasks:
    - import_role:
        name: linux
