---
mssql_network: mysql1
mssql_state: started
app_name: mssql1
app_port: 1433
app_host_port: 1434
base_path: "{{ansible_env.HOME}}/docker2/apps"
target_path: "{{base_path}}/{{app_name}}"
mssql_backups_dir: "{{target_path}}/backups"
mssql_conf_dir: "{{target_path}}/conf"
mssql_lib_dir: /var/mysql/lib
mssql_root_password: 'testst1234'
